// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIkk4yqZ6J9axEpUlrUesA0cBn1jDlRJg',
    appId: '1:451006927952:web:3112549caf7285ee0c2d55',
    messagingSenderId: '451006927952',
    projectId: 'quant-221f9',
    authDomain: 'quant-221f9.firebaseapp.com',
    storageBucket: 'quant-221f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRJDr_aD1FRWRA03f4Pc7K4Pdr917phi0',
    appId: '1:451006927952:android:de4a0147f070576e0c2d55',
    messagingSenderId: '451006927952',
    projectId: 'quant-221f9',
    storageBucket: 'quant-221f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdoBFGVOMJdAgGzUqwp3mgCE5IfC-Xovs',
    appId: '1:451006927952:ios:6f698f62bf81824e0c2d55',
    messagingSenderId: '451006927952',
    projectId: 'quant-221f9',
    storageBucket: 'quant-221f9.appspot.com',
    iosBundleId: 'com.example.quant',
  );
}
